### ISSUE TITLE
vercel deployment issue

### ISSUE THREAD

**Issue by leonogas** [frontendweb3/minimalist#1]
Hi guys,

I tried to deploy this now to vercel and I got:

<img width="814" alt="Screenshot 2023-11-08 at 12 27 58" src="https://github.com/frontendweb3/minimalist/assets/8076621/c289ee81-9ed6-4c8f-b2d9-1b08a35d5e8b">

can you deploy correctly?

thanks

**Comment by leonogas** [comment]
any udate on this?

**Comment by officialrajdeepsingh** [comment]
> Sorry for late reply. @leonogas 

To solve the issue, run the development server and then run the production server. The development serve create a [`.contentlayer` folder](https://contentlayer.dev/blog/beta#how-contentlayer-works).

```bash
# first run dev development
pnpm dev
# then run production
pnpm build
```
